// <auto-generated />
using System;
using AspnetCoreMvcFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspnetCoreMvcFull.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905155130_InitialCreate3")]
    partial class InitialCreate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ArsipSurat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("KategoriSuratId")
                        .HasColumnType("integer");

                    b.Property<string>("NomorSurat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("WaktuPengarsipan")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KategoriSuratId");

                    b.ToTable("ArsipSurats");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.KategoriSurat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NamaKategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("KategoriSurats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Keterangan = "Surat bersifat undangan resmi.",
                            NamaKategori = "Undangan"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Keterangan = "Surat bersifat pengumuman.",
                            NamaKategori = "Pengumuman"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Keterangan = "Surat internal antar dinas.",
                            NamaKategori = "Nota Dinas"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Keterangan = "Surat bersifat pemberitahuan informasi.",
                            NamaKategori = "Pemberitahuan"
                        });
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ArsipSurat", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.KategoriSurat", "KategoriSurat")
                        .WithMany("ArsipSurats")
                        .HasForeignKey("KategoriSuratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriSurat");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.KategoriSurat", b =>
                {
                    b.Navigation("ArsipSurats");
                });
#pragma warning restore 612, 618
        }
    }
}
