--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Postgres.app)
-- Dumped by pg_dump version 17.4 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ArsipSurats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ArsipSurats" (
    "Id" integer NOT NULL,
    "NomorSurat" character varying(50) NOT NULL,
    "Judul" character varying(200) NOT NULL,
    "WaktuPengarsipan" timestamp with time zone NOT NULL,
    "FilePath" text NOT NULL,
    "KategoriSuratId" integer NOT NULL
);


ALTER TABLE public."ArsipSurats" OWNER TO postgres;

--
-- Name: ArsipSurats_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ArsipSurats" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ArsipSurats_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: KategoriSurats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."KategoriSurats" (
    "Id" integer NOT NULL,
    "NamaKategori" character varying(100) NOT NULL,
    "Keterangan" character varying(255) NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."KategoriSurats" OWNER TO postgres;

--
-- Name: KategoriSurats_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."KategoriSurats" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."KategoriSurats_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: ArsipSurats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ArsipSurats" ("Id", "NomorSurat", "Judul", "WaktuPengarsipan", "FilePath", "KategoriSuratId") FROM stdin;
25	240/SMD.2/2025	Surat Undangan 2	2025-09-06 02:03:29.941259+08	uploads/surat/176e7ff3-868c-4d29-a9de-21230dd9e52e_surat-undangan-2.pdf	13
17	001/SGT.1/2025	Surat Pemberitahuan 1	2025-09-06 01:57:04.020388+08	uploads/surat/e414043c-00e6-4afb-81dd-002c5ed712e5_surat-pemberitahuan-1.pdf	4
18	002/SGT.1/2025	Surat Pemberitahuan 2	2025-09-06 01:57:34.774274+08	uploads/surat/20e91479-4f02-43ff-a7e5-c1932e4a7bcf_surat-pemberitahuan-1.pdf	4
19	115/BPN.1/2025	Nota Dinas 1	2025-09-06 01:58:18.842043+08	uploads/surat/f35e4403-cee0-4a64-bbaa-c025380166dd_surat-pemberitahuan-1.pdf	3
20	116/BPN.1/2025	Nota Dinas 2	2025-09-06 01:58:36.506026+08	uploads/surat/c3914e33-14aa-4180-b871-52c224eecde6_surat-pemberitahuan-1.pdf	3
21	239/SMD.2/2025	Surat Undangan 1	2025-09-06 01:59:13.791559+08	uploads/surat/11ce0503-8369-43ae-9803-641d1d1dc265_surat-pemberitahuan-1.pdf	13
\.


--
-- Data for Name: KategoriSurats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."KategoriSurats" ("Id", "NamaKategori", "Keterangan", "IsDeleted") FROM stdin;
3	Nota Dinas	Surat internal antar dinas.	f
4	Pemberitahuan	Surat bersifat pemberitahuan informasi.	f
1	Undangan	Surat bersifat undangan resmi.	t
10	Undangan	tes duplikat undangan	t
11	Undangan	tes duplikat undangan	t
12	Undangan	tes duplikat undangan	t
2	Pengumuman	Surat bersifat pengumuman.	t
14	Pengumuman2	testesttest	t
13	Undangan	Surat bersifat undangan resmi.	f
15	Pengumuman	Surat bersifat pengumuman.	f
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250905041512_InitialCreate	8.0.8
20250905150636_InitialCreate2	8.0.8
20250905155130_InitialCreate3	8.0.8
\.


--
-- Name: ArsipSurats_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ArsipSurats_Id_seq"', 25, true);


--
-- Name: KategoriSurats_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."KategoriSurats_Id_seq"', 15, true);


--
-- Name: ArsipSurats PK_ArsipSurats; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ArsipSurats"
    ADD CONSTRAINT "PK_ArsipSurats" PRIMARY KEY ("Id");


--
-- Name: KategoriSurats PK_KategoriSurats; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."KategoriSurats"
    ADD CONSTRAINT "PK_KategoriSurats" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_ArsipSurats_KategoriSuratId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ArsipSurats_KategoriSuratId" ON public."ArsipSurats" USING btree ("KategoriSuratId");


--
-- Name: ArsipSurats FK_ArsipSurats_KategoriSurats_KategoriSuratId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ArsipSurats"
    ADD CONSTRAINT "FK_ArsipSurats_KategoriSurats_KategoriSuratId" FOREIGN KEY ("KategoriSuratId") REFERENCES public."KategoriSurats"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

